spring:
  datasource:
    username: ${DB_HEROKU_USERNAME:postgres}
    password: ${DB_HEROKU_PASSWORD:postgres}
    url: ${DB_HEROKU_URL:jdbc:postgresql://localhost:5432/marketplace}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_FROM:pasha16.ua@gmail.com}
    password: bwat ierf mmnl jgfn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signing: ${JWT_SIGNING:secret}
  expiration: 6000000

token:
  valid:
    duration: 86400000

mail:
  link:
    to:
      confirm-email: ${LINK_TO_CONFIRM_EMAIL:http://localhost:8080/api/v1/email/confirm-email/}
      change-password: ${LINK_TO_CHANGE_PASSWORD:link to change password}

jasypt:
  encryptor:
    password: yourEncryptionPassword

